import React from 'react';
import { 
  Library, AlertCircle, Monitor, Calendar, MessageCircle, Check, CheckCircle, 
  ChevronDown, ChevronRight, ChevronUp, X, ExternalLink, Eye, EyeOff, Film, 
  FolderOpen, LayoutGrid, Heart, Info, List, Lock, LogOut, Music, SlidersHorizontal, 
  Play, SkipBack, SkipForward, StepBack, StepForward, Gauge, Plus, RefreshCw, 
  CornerDownLeft, Search, Settings, ShieldCheck, Star, Subtitles, Sun, ArrowLeftRight, ArrowLeft,
  MonitorOff, Clock, Tv, Volume2, TriangleAlert, Wifi, Pause, Server, Cloud, Layers, PlayCircle, StarOff, MoreVertical,
  Zap, FastForward, Cpu, Brush, Trash, FileText, MonitorPlay, CloudOff,
  HardDrive, Globe, Mail, Key, Delete, Copy, Activity, ChartLine, CloudDownload,
  Aperture, Type, XCircle, Sparkles
} from 'lucide-react-native';

const ICON_MAP: Record<string, any> = {
    "television-play": MonitorPlay,
    "flash-outline": Zap,
    "server-outline": Server,
    "play-forward-outline": FastForward,
    "lock-closed-outline": Lock,
    "hardware-chip-outline": Cpu,
    "brush-outline": Brush,
    "trash-outline": Trash,
    "document-text-outline": FileText,
    "albums-outline": Library,
    "alert-circle-outline": AlertCircle,
    "aspect-ratio": Monitor,
    "calendar-outline": Calendar,
    "calendar": Calendar,
    "chatbubble-ellipses-outline": MessageCircle,
    "checkmark": Check,
    "checkmark-circle": CheckCircle,
    "checkmark-circle-outline": CheckCircle,
    "chevron-down": ChevronDown,
    "chevron-forward": ChevronRight,
    "chevron-up": ChevronUp,
    "close": X,
    // The player's "no subtitles / no audio track" option asks for this one.
    // `XCircle` rather than plain `X`, matching `checkmark-circle-outline`
    // above — the `-circle-outline` suffix means the ringed variant.
    "close-circle-outline": XCircle,
    "x": X,
    "external-link": ExternalLink,
    "eye-outline": Eye,
    "eye-off-outline": EyeOff,
    "film-outline": Film,
    "filmstrip": Film,
    "film": Film,
    "folder-open-outline": FolderOpen,
    "grid": LayoutGrid,
    "heart": Heart,
    "information-circle-outline": Info,
    "list-outline": List,
    "list": List,
    "lock": Lock,
    "lock-closed": Lock,
    "log-out-outline": LogOut,
    "musical-notes-outline": Music,
    "options-outline": SlidersHorizontal,
    "play": Play,
    "pause": Pause,
    "play-back": SkipBack,
    "play-forward": SkipForward,
    "play-skip-back": StepBack,
    "play-skip-forward": StepForward,
    "play-speed": Gauge,
    "play-circle-outline": PlayCircle,
    "plus": Plus,
    "refresh": RefreshCw,
    "refresh-cw": RefreshCw,
    "return-down-back": CornerDownLeft,
    "search": Search,
    "sparkles-outline": Sparkles,
    "search-outline": Search,
    "settings": Settings,
    "settings-outline": Settings,
    "shield-checkmark": ShieldCheck,
    "speedometer-outline": Gauge,
    "star": Star,
    "star-outline": StarOff,
    "subtitles-outline": Subtitles,
    "sunny": Sun,
    "swap-horizontal": ArrowLeftRight,
    "arrow-back": ArrowLeft,
    "arrow-back-outline": ArrowLeft,
    "arrow-left": ArrowLeft,
    "arrow-left-outline": ArrowLeft,
    "television-off": MonitorOff,
    "time-outline": Clock,
    "tv": Tv,
    "tv-outline": Tv,
    "volume-high": Volume2,
    "warning": TriangleAlert,
    "warning-outline": TriangleAlert,
    "wifi-outline": Wifi,
    "server": Server,
    "cloud": Cloud,
    "cloud-off": CloudOff,
    "cloud-off-outline": CloudOff,
    "save": HardDrive,
    "save-outline": HardDrive,
    "globe": Globe,
    "globe-outline": Globe,
    "shield-checkmark-outline": ShieldCheck,
    "mail": Mail,
    "mail-outline": Mail,
    "layers": Layers,
    "ellipsis-vertical": MoreVertical,
    "key": Key,
    "key-outline": Key,
    "delete": Delete,
    "copy": Copy,
    "copy-outline": Copy,
    "pulse": Activity,
    "pulse-outline": Activity,
    "analytics": ChartLine,
    "analytics-outline": ChartLine,
    "cloud-download": CloudDownload,
    "cloud-download-outline": CloudDownload,
    "download": CloudDownload,
    "aperture": Aperture,
    "musical-notes": Music,
    "text": Type,
};

export function DynamicIcon({ name, size, color, style, ...props }: any) {
  if (!name) return null;
  // If the name is already a component (some places we passed the component directly), render it
  if (typeof name === 'function' || typeof name === 'object') {
    const IconComponent = name;
    return <IconComponent size={size} color={color} style={style} {...props} />;
  }
  
  const normalized = typeof name === 'string' ? name.replace(/-outline$/, '') : name;
  const Icon = ICON_MAP[name] || ICON_MAP[normalized];
  if (!Icon) {
    console.warn(`DynamicIcon: missing mapping for icon "${name}"`);
    return null;
  }
  return <Icon size={size} color={color} style={style} {...props} />;
}
